### ISSUE TITLE
Find a scala library to replace MCProtocolLib

### ISSUE THREAD

**Issue by TheElectronWill** [tuubes/TuubesCore#13]
## Context

Photon currently uses the MCProtocolLib library to handle the game packets. This library aims to provide ready-to-use classes for Minecraft server and clients, which is a nice goal. Unfortunately, it doesn't fit well enough with Photon, that's why I forked it to apply some necessary modifications (and a few that are "just" performance bonuses, I admit).

## Current problem

Each time the game protocol changes or a bug is fixed in the lib, I need to adapt these changes to Photon and to merge them with my fork of MCProtocolLib. This is a lot of boring work, and I feel that I could use my time much better than this.

## Proposal

Writing my own protocol library, for Photon, with Photon. Maybe not for the Alpha 0.5 but for the next release. The "low-level" networking and buffering part will be handled by [a separate library](https://github.com/TheElectronWill/Niol) and could be used without Photon. The game protocol will be implemented on top of this library, directly in the Photon-Server repository.

**Comment by TheElectronWill** [comment]
## Tasks To Do
- [x] Program [a new scala library](https://github.com/TheElectronWill/Niol/tree/1.0) to ease the development of TCP servers: manage the Selector, handle the incomplete reads and writes, etc.
- [x] Test it with a simple protocol.
- [x] Test it with the Minecraft protocol.
- [x] Implement the missing features

**Comment by TheElectronWill** [comment]
~~The [Niol library](https://github.com/TheElectronWill/Niol) is now tested and ready-to-use!
I'll begin to implement the mc protocol in Photon.~~
There seems to be a few annoying bugs and missing features.

**Comment by TheElectronWill** [comment]
- [ ] Basic TCP connection
- [ ] Handshaking
- [ ] Status (ping)
- [ ] Encryption
- [ ] Authentication
- [ ] Compression
- [ ] Join Game

**Comment by TheElectronWill** [comment]
[Niol v1.3](https://github.com/TheElectronWill/Niol) should have all the features we need. I'm closing.
