### ISSUE TITLE
Scala "rewrite"

### ISSUE THREAD

**Issue by TheElectronWill** [tuubes/TuubesCore#9]
# Goals:
- Make the code a shorter, cleaner and easier-to-use.
- Accelerate the future development of the project (code easy to maintain and to extend)

# Tasks to do:
- [x] Merge what was called "api" and "impl". The implementation details will be hidden to the plugins by fine-tuned scala access modifiers. This is a **huge** work. Below is the current status of the packages:
  - [x] block
  - [x] command
  - [x] entity
  - [x] event
  - [x] item
  - [x] plugin
  - [x] server
  - [x] user
  - [x] world
  - [x] runtime
  - [x] network
- [x] Use scala's `Option` and `Try` instead of java's `null` and exceptions.
- [x] Use [NightConfig](https://github.com/TheElectronWill/Night-Config) version 3.0.1
- [x] Use [scala-logging](https://github.com/typesafehub/scala-logging) instead of slf4j
_More tasks may be necessary to fulfill the goals, fell free to suggest something that isn't listed_

# Non-goals:
We do **not** want to:
- Rewrite systematically all the code in Scala (that's why I put "rewrite" in quotes). When the java code is perfectly clear, short (and a rewrite in scala doesn't make it much shorter), efficient and easily usable by the scala code, it doesn't have to be rewritten.
- Use Scala for the Photon-ProtocolLib. _(this may be done in a later version)_
- Provide a Java API for the plugins, on top of the scala project, to hide scala-only features (like functions with symbols in their names, or advanced access modifiers that translate to public from the Java point of view) to the java developers. _(this may be done in a later version)_
- Use advanced scala features just because "they are cool". Indeed they are :-) But please keep the code simple and intelligible.

**Comment by Bluexin** [comment]
How about considering Kotlin? I think it brings a lot of the nice features of Scala while maintaining total Java interop.

**Comment by TheElectronWill** [comment]
@Bluexin Kotlin is an interesting language, but not as powerful nor flexible as Scala (probably because Kotlin wants to stay closer to Java). Since scala has java interop too, my choice is made.

**Comment by Bluexin** [comment]
Fair enough ^-^
Haven't done much scala myself, but heard the java interop could be a bit iffy at times
